import Head from "next/head";
import { useState, useEffect } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [data, setData] = useState([]);
  const precio = data.result?.Tarifas.Oro[2].Productos[0].Precio / 1000;
  const precioDolar =
    data.result?.Tarifas.Divisas_Compra[28].Productos[0].Precio / 1000;
  useEffect(() => {
    fetch("https://quickgold.es/archivos-cache/Fixingvalencia.txt")
      .then((response) => response.json())
      .then((data) => {
        setData(data);
      });
  }, []);
  console.log(data.result?.Tarifas.Oro[2].Productos[0].Precio / 1000);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Web en Construcción <p>CurrencyMarket!</p>
        </h1>
        <div className="container">
          <h1>Precio USD = {precioDolar.toFixed(4)}$</h1>
          <h1>Precio oro 18k = {precio.toFixed(2)}€</h1>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>
          Powered by <span className={styles.logo}>Quickgold</span>
        </p>
      </footer>
    </div>
  );
}
